---
- hosts: all
  become: yes
  tasks: 
  - name: updating the packages
    apt: 
      update_cache: yes
  #nodejs specific settings
- hosts: app
  become: yes
  tasks:
  - name: installing nodejs and npm
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - nodejs
        - npm
        - build-essential
  - name: creating template with dynamic content
    template:
      src: "templates/hello.js.j2"
      dest: "/home/ubuntu/"
      mode: "ugo=rwx"
  - name: run the script
    command: "/home/ubuntu/./hello.js"
  

  
  
  
    